#!/usr/bin/env node
// node cli/regenerate.mjs [--check]: rebuilds what is generated from the
// command modules, so a task that adds a command writes only its own files.
//
//   src/usage/commands/index.ts  every module in src/usage/commands/, the
//                                declarations the CLI and the Worker read
//   cli/commands/index.mjs       every handler in cli/commands/, which the
//                                CLI alone loads
//   test/fixtures/cli/help.txt, usage.json and guide.txt
//                                what `atelier help`, each `atelier COMMAND
//                                --help` and `atelier guide` print, run with an
//                                empty config so no machine's projects appear
//
// Each index lists its folder's modules in name order and each fixture is
// the CLI's own output, so the result depends only on the files: a second run
// changes nothing. A module that fails to register (a duplicate name or alias,
// a form of another command) or a CLI run that fails ends it with status 1,
// naming the cause, and puts back any index it had written. --check writes
// nothing and exits 1 when anything would change, naming each file.

import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SPECS = "src/usage/commands", HANDLERS = "cli/commands";
const HEADER = "// Generated by `node cli/regenerate.mjs` from the modules in this folder; do not edit.";

// The command modules in a folder, by name: every file with the extension
// but the index. A folder holds command modules alone, so the usage-reporting
// modules (src/usage/*.ts, cli/usage.mjs) are never among them.
export function commandFiles(root, folder, extension) {
  const dir = join(root, folder);
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter((f) => f.endsWith(extension) && f !== `index${extension}` && !f.endsWith(`.d${extension}`)).map((f) => f.slice(0, -extension.length)).sort();
}

// An import binding for a command name: new and other reserved words, and
// names with hyphens, are not identifiers.
const binding = (name) => `command_${name.replaceAll("-", "_")}`;

export function specIndex(names) {
  return [
    HEADER,
    'import type { CommandModule } from "../command.ts";',
    ...names.map((n) => `import ${binding(n)} from "./${n}.ts";`),
    "",
    "export const COMMAND_MODULES: CommandModule[] = [",
    ...names.map((n) => `  { path: "${SPECS}/${n}.ts", spec: ${binding(n)} },`),
    "];",
    "",
  ].join("\n");
}

export function handlerIndex(names) {
  return [
    HEADER,
    ...names.map((n) => `import ${binding(n)} from "./${n}.mjs";`),
    "",
    "export const HANDLER_MODULES = [",
    ...names.map((n) => `  { path: "${HANDLERS}/${n}.mjs", run: ${binding(n)} },`),
    "];",
    "",
  ].join("\n");
}

// The CLI's output for one run, from an empty config folder outside any
// checkout; a run that fails or writes to stderr is an error.
function cli(root, args, config) {
  const r = spawnSync(process.execPath, [join(root, "cli/atelier.mjs"), ...args], {
    cwd: config, encoding: "utf8", env: { ...process.env, ATELIER_CONFIG_DIR: config },
  });
  if (r.error || r.status !== 0 || r.stderr) throw new Error(`atelier ${args.join(" ")} failed (status ${r.status}): ${(r.stderr || r.error?.message || "").trim()}`);
  return r.stdout;
}

async function fixtures(root) {
  const config = mkdtempSync(join(tmpdir(), "atelier-regenerate-"));
  try {
    // A child process reads the indexes as written, never a cached import,
    // and registers every declaration and handler, as the CLI does.
    const url = (file) => JSON.stringify(pathToFileURL(join(root, file)).href);
    const list = spawnSync(process.execPath, ["--input-type=module", "-e",
      `try { await import(${url("cli/atelier.mjs")}); const { COMMAND_USAGE } = await import(${url("cli/help.mjs")}); console.log(JSON.stringify(Object.keys(COMMAND_USAGE).sort())); }
      catch (error) { process.stderr.write(error.message + "\\n"); process.exit(1); }`,
    ], { cwd: config, encoding: "utf8", env: { ...process.env, ATELIER_CONFIG_DIR: config } });
    if (list.status !== 0) throw new Error(`the command modules do not load: ${list.stderr.trim()}`);
    const usage = {};
    for (const cmd of JSON.parse(list.stdout)) usage[cmd] = cli(root, [cmd, "--help"], config);
    return {
      "test/fixtures/cli/help.txt": cli(root, ["help"], config),
      "test/fixtures/cli/usage.json": JSON.stringify(usage, null, 2) + "\n",
      "test/fixtures/cli/guide.txt": cli(root, ["guide"], config),
    };
  } finally {
    rmSync(config, { recursive: true, force: true });
  }
}

const read = (root, file) => (existsSync(join(root, file)) ? readFileSync(join(root, file), "utf8") : null);

// Rebuilds the indexes and fixtures under root; returns the files changed.
// With check, writes nothing beyond what it puts back.
export async function regenerate(root = ROOT, { check = false } = {}) {
  const indexes = {
    [`${SPECS}/index.ts`]: specIndex(commandFiles(root, SPECS, ".ts")),
    [`${HANDLERS}/index.mjs`]: handlerIndex(commandFiles(root, HANDLERS, ".mjs")),
  };
  const before = Object.fromEntries(Object.keys(indexes).map((f) => [f, read(root, f)]));
  const changed = Object.keys(indexes).filter((f) => before[f] !== indexes[f]);
  // The fixtures come from the CLI, which reads the indexes from disk.
  for (const f of changed) writeFileSync(join(root, f), indexes[f]);
  let generated;
  try {
    generated = await fixtures(root);
  } catch (error) {
    for (const f of changed) before[f] === null ? rmSync(join(root, f)) : writeFileSync(join(root, f), before[f]);
    throw error;
  } finally {
    if (check) for (const f of changed) before[f] === null ? rmSync(join(root, f), { force: true }) : writeFileSync(join(root, f), before[f]);
  }
  for (const [f, text] of Object.entries(generated)) {
    if (read(root, f) === text) continue;
    changed.push(f);
    if (!check) writeFileSync(join(root, f), text);
  }
  return changed;
}

if (process.argv[1] && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))) {
  const check = process.argv.includes("--check");
  const unknown = process.argv.slice(2).filter((a) => a !== "--check");
  if (unknown.length) {
    process.stderr.write(`regenerate: unknown argument ${unknown[0]}; usage: node cli/regenerate.mjs [--check]\n`);
    process.exit(1);
  }
  try {
    const changed = await regenerate(ROOT, { check });
    if (!changed.length) console.log("regenerate: every index and fixture is up to date");
    else if (check) { console.log(`regenerate: out of date: ${changed.join(", ")}; run node cli/regenerate.mjs`); process.exit(1); }
    else console.log(`regenerate: wrote ${changed.join(", ")}`);
  } catch (error) {
    process.stderr.write(`regenerate: ${error.message}\n`);
    process.exit(1);
  }
}
