// Generated by `node cli/regenerate.mjs` from the modules in this folder; do not edit.
import command_abandon from "./abandon.mjs";
import command_accept from "./accept.mjs";
import command_adopt from "./adopt.mjs";
import command_approvals from "./approvals.mjs";
import command_approve from "./approve.mjs";
import command_base_token from "./base-token.mjs";
import command_block from "./block.mjs";
import command_check from "./check.mjs";
import command_claim from "./claim.mjs";
import command_decide from "./decide.mjs";
import command_decisions from "./decisions.mjs";
import command_defect from "./defect.mjs";
import command_diff from "./diff.mjs";
import command_dispatch from "./dispatch.mjs";
import command_done from "./done.mjs";
import command_edit from "./edit.mjs";
import command_finding from "./finding.mjs";
import command_finish from "./finish.mjs";
import command_gc from "./gc.mjs";
import command_guide from "./guide.mjs";
import command_handoff from "./handoff.mjs";
import command_help from "./help.mjs";
import command_inbox from "./inbox.mjs";
import command_init from "./init.mjs";
import command_integrated from "./integrated.mjs";
import command_integration_failed from "./integration-failed.mjs";
import command_land from "./land.mjs";
import command_login from "./login.mjs";
import command_ls from "./ls.mjs";
import command_merge from "./merge.mjs";
import command_models from "./models.mjs";
import command_new from "./new.mjs";
import command_notes_remote from "./notes-remote.mjs";
import command_open from "./open.mjs";
import command_ops from "./ops.mjs";
import command_owners from "./owners.mjs";
import command_plan from "./plan.mjs";
import command_projects from "./projects.mjs";
import command_publish from "./publish.mjs";
import command_push from "./push.mjs";
import command_queue from "./queue.mjs";
import command_read_token from "./read-token.mjs";
import command_receipt from "./receipt.mjs";
import command_refresh_failed from "./refresh-failed.mjs";
import command_refreshed from "./refreshed.mjs";
import command_release from "./release.mjs";
import command_report from "./report.mjs";
import command_revert from "./revert.mjs";
import command_review from "./review.mjs";
import command_review_claim from "./review-claim.mjs";
import command_review_release from "./review-release.mjs";
import command_review_unparsable from "./review-unparsable.mjs";
import command_run_report from "./run-report.mjs";
import command_runner from "./runner.mjs";
import command_served from "./served.mjs";
import command_ship from "./ship.mjs";
import command_show from "./show.mjs";
import command_showcase from "./showcase.mjs";
import command_start from "./start.mjs";
import command_status from "./status.mjs";
import command_submit from "./submit.mjs";
import command_sync from "./sync.mjs";
import command_token from "./token.mjs";
import command_unblock from "./unblock.mjs";
import command_undispatch from "./undispatch.mjs";
import command_unwrap from "./unwrap.mjs";
import command_update from "./update.mjs";
import command_wrap from "./wrap.mjs";

export const HANDLER_MODULES = [
  { path: "cli/commands/abandon.mjs", run: command_abandon },
  { path: "cli/commands/accept.mjs", run: command_accept },
  { path: "cli/commands/adopt.mjs", run: command_adopt },
  { path: "cli/commands/approvals.mjs", run: command_approvals },
  { path: "cli/commands/approve.mjs", run: command_approve },
  { path: "cli/commands/base-token.mjs", run: command_base_token },
  { path: "cli/commands/block.mjs", run: command_block },
  { path: "cli/commands/check.mjs", run: command_check },
  { path: "cli/commands/claim.mjs", run: command_claim },
  { path: "cli/commands/decide.mjs", run: command_decide },
  { path: "cli/commands/decisions.mjs", run: command_decisions },
  { path: "cli/commands/defect.mjs", run: command_defect },
  { path: "cli/commands/diff.mjs", run: command_diff },
  { path: "cli/commands/dispatch.mjs", run: command_dispatch },
  { path: "cli/commands/done.mjs", run: command_done },
  { path: "cli/commands/edit.mjs", run: command_edit },
  { path: "cli/commands/finding.mjs", run: command_finding },
  { path: "cli/commands/finish.mjs", run: command_finish },
  { path: "cli/commands/gc.mjs", run: command_gc },
  { path: "cli/commands/guide.mjs", run: command_guide },
  { path: "cli/commands/handoff.mjs", run: command_handoff },
  { path: "cli/commands/help.mjs", run: command_help },
  { path: "cli/commands/inbox.mjs", run: command_inbox },
  { path: "cli/commands/init.mjs", run: command_init },
  { path: "cli/commands/integrated.mjs", run: command_integrated },
  { path: "cli/commands/integration-failed.mjs", run: command_integration_failed },
  { path: "cli/commands/land.mjs", run: command_land },
  { path: "cli/commands/login.mjs", run: command_login },
  { path: "cli/commands/ls.mjs", run: command_ls },
  { path: "cli/commands/merge.mjs", run: command_merge },
  { path: "cli/commands/models.mjs", run: command_models },
  { path: "cli/commands/new.mjs", run: command_new },
  { path: "cli/commands/notes-remote.mjs", run: command_notes_remote },
  { path: "cli/commands/open.mjs", run: command_open },
  { path: "cli/commands/ops.mjs", run: command_ops },
  { path: "cli/commands/owners.mjs", run: command_owners },
  { path: "cli/commands/plan.mjs", run: command_plan },
  { path: "cli/commands/projects.mjs", run: command_projects },
  { path: "cli/commands/publish.mjs", run: command_publish },
  { path: "cli/commands/push.mjs", run: command_push },
  { path: "cli/commands/queue.mjs", run: command_queue },
  { path: "cli/commands/read-token.mjs", run: command_read_token },
  { path: "cli/commands/receipt.mjs", run: command_receipt },
  { path: "cli/commands/refresh-failed.mjs", run: command_refresh_failed },
  { path: "cli/commands/refreshed.mjs", run: command_refreshed },
  { path: "cli/commands/release.mjs", run: command_release },
  { path: "cli/commands/report.mjs", run: command_report },
  { path: "cli/commands/revert.mjs", run: command_revert },
  { path: "cli/commands/review.mjs", run: command_review },
  { path: "cli/commands/review-claim.mjs", run: command_review_claim },
  { path: "cli/commands/review-release.mjs", run: command_review_release },
  { path: "cli/commands/review-unparsable.mjs", run: command_review_unparsable },
  { path: "cli/commands/run-report.mjs", run: command_run_report },
  { path: "cli/commands/runner.mjs", run: command_runner },
  { path: "cli/commands/served.mjs", run: command_served },
  { path: "cli/commands/ship.mjs", run: command_ship },
  { path: "cli/commands/show.mjs", run: command_show },
  { path: "cli/commands/showcase.mjs", run: command_showcase },
  { path: "cli/commands/start.mjs", run: command_start },
  { path: "cli/commands/status.mjs", run: command_status },
  { path: "cli/commands/submit.mjs", run: command_submit },
  { path: "cli/commands/sync.mjs", run: command_sync },
  { path: "cli/commands/token.mjs", run: command_token },
  { path: "cli/commands/unblock.mjs", run: command_unblock },
  { path: "cli/commands/undispatch.mjs", run: command_undispatch },
  { path: "cli/commands/unwrap.mjs", run: command_unwrap },
  { path: "cli/commands/update.mjs", run: command_update },
  { path: "cli/commands/wrap.mjs", run: command_wrap },
];
