// Generated by `node cli/regenerate.mjs` from the modules in this folder; do not edit.
import type { CommandModule } from "../command.ts";
import command_abandon from "./abandon.ts";
import command_accept from "./accept.ts";
import command_adopt from "./adopt.ts";
import command_approvals from "./approvals.ts";
import command_approve from "./approve.ts";
import command_base_token from "./base-token.ts";
import command_block from "./block.ts";
import command_check from "./check.ts";
import command_claim from "./claim.ts";
import command_decide from "./decide.ts";
import command_decisions from "./decisions.ts";
import command_defect from "./defect.ts";
import command_diff from "./diff.ts";
import command_dispatch from "./dispatch.ts";
import command_done from "./done.ts";
import command_edit from "./edit.ts";
import command_finding from "./finding.ts";
import command_finish from "./finish.ts";
import command_gc from "./gc.ts";
import command_guide from "./guide.ts";
import command_handoff from "./handoff.ts";
import command_help from "./help.ts";
import command_inbox from "./inbox.ts";
import command_init from "./init.ts";
import command_integrated from "./integrated.ts";
import command_integration_failed from "./integration-failed.ts";
import command_land from "./land.ts";
import command_login from "./login.ts";
import command_ls from "./ls.ts";
import command_merge from "./merge.ts";
import command_models from "./models.ts";
import command_new from "./new.ts";
import command_notes_remote from "./notes-remote.ts";
import command_open from "./open.ts";
import command_ops from "./ops.ts";
import command_owners from "./owners.ts";
import command_plan from "./plan.ts";
import command_projects from "./projects.ts";
import command_publish from "./publish.ts";
import command_push from "./push.ts";
import command_queue from "./queue.ts";
import command_read_token from "./read-token.ts";
import command_receipt from "./receipt.ts";
import command_refresh_failed from "./refresh-failed.ts";
import command_refreshed from "./refreshed.ts";
import command_release from "./release.ts";
import command_report from "./report.ts";
import command_revert from "./revert.ts";
import command_review from "./review.ts";
import command_review_claim from "./review-claim.ts";
import command_review_release from "./review-release.ts";
import command_review_unparsable from "./review-unparsable.ts";
import command_run_report from "./run-report.ts";
import command_runner from "./runner.ts";
import command_served from "./served.ts";
import command_ship from "./ship.ts";
import command_show from "./show.ts";
import command_showcase from "./showcase.ts";
import command_start from "./start.ts";
import command_status from "./status.ts";
import command_submit from "./submit.ts";
import command_sync from "./sync.ts";
import command_token from "./token.ts";
import command_unblock from "./unblock.ts";
import command_undispatch from "./undispatch.ts";
import command_unwrap from "./unwrap.ts";
import command_update from "./update.ts";
import command_wrap from "./wrap.ts";

export const COMMAND_MODULES: CommandModule[] = [
  { path: "src/usage/commands/abandon.ts", spec: command_abandon },
  { path: "src/usage/commands/accept.ts", spec: command_accept },
  { path: "src/usage/commands/adopt.ts", spec: command_adopt },
  { path: "src/usage/commands/approvals.ts", spec: command_approvals },
  { path: "src/usage/commands/approve.ts", spec: command_approve },
  { path: "src/usage/commands/base-token.ts", spec: command_base_token },
  { path: "src/usage/commands/block.ts", spec: command_block },
  { path: "src/usage/commands/check.ts", spec: command_check },
  { path: "src/usage/commands/claim.ts", spec: command_claim },
  { path: "src/usage/commands/decide.ts", spec: command_decide },
  { path: "src/usage/commands/decisions.ts", spec: command_decisions },
  { path: "src/usage/commands/defect.ts", spec: command_defect },
  { path: "src/usage/commands/diff.ts", spec: command_diff },
  { path: "src/usage/commands/dispatch.ts", spec: command_dispatch },
  { path: "src/usage/commands/done.ts", spec: command_done },
  { path: "src/usage/commands/edit.ts", spec: command_edit },
  { path: "src/usage/commands/finding.ts", spec: command_finding },
  { path: "src/usage/commands/finish.ts", spec: command_finish },
  { path: "src/usage/commands/gc.ts", spec: command_gc },
  { path: "src/usage/commands/guide.ts", spec: command_guide },
  { path: "src/usage/commands/handoff.ts", spec: command_handoff },
  { path: "src/usage/commands/help.ts", spec: command_help },
  { path: "src/usage/commands/inbox.ts", spec: command_inbox },
  { path: "src/usage/commands/init.ts", spec: command_init },
  { path: "src/usage/commands/integrated.ts", spec: command_integrated },
  { path: "src/usage/commands/integration-failed.ts", spec: command_integration_failed },
  { path: "src/usage/commands/land.ts", spec: command_land },
  { path: "src/usage/commands/login.ts", spec: command_login },
  { path: "src/usage/commands/ls.ts", spec: command_ls },
  { path: "src/usage/commands/merge.ts", spec: command_merge },
  { path: "src/usage/commands/models.ts", spec: command_models },
  { path: "src/usage/commands/new.ts", spec: command_new },
  { path: "src/usage/commands/notes-remote.ts", spec: command_notes_remote },
  { path: "src/usage/commands/open.ts", spec: command_open },
  { path: "src/usage/commands/ops.ts", spec: command_ops },
  { path: "src/usage/commands/owners.ts", spec: command_owners },
  { path: "src/usage/commands/plan.ts", spec: command_plan },
  { path: "src/usage/commands/projects.ts", spec: command_projects },
  { path: "src/usage/commands/publish.ts", spec: command_publish },
  { path: "src/usage/commands/push.ts", spec: command_push },
  { path: "src/usage/commands/queue.ts", spec: command_queue },
  { path: "src/usage/commands/read-token.ts", spec: command_read_token },
  { path: "src/usage/commands/receipt.ts", spec: command_receipt },
  { path: "src/usage/commands/refresh-failed.ts", spec: command_refresh_failed },
  { path: "src/usage/commands/refreshed.ts", spec: command_refreshed },
  { path: "src/usage/commands/release.ts", spec: command_release },
  { path: "src/usage/commands/report.ts", spec: command_report },
  { path: "src/usage/commands/revert.ts", spec: command_revert },
  { path: "src/usage/commands/review.ts", spec: command_review },
  { path: "src/usage/commands/review-claim.ts", spec: command_review_claim },
  { path: "src/usage/commands/review-release.ts", spec: command_review_release },
  { path: "src/usage/commands/review-unparsable.ts", spec: command_review_unparsable },
  { path: "src/usage/commands/run-report.ts", spec: command_run_report },
  { path: "src/usage/commands/runner.ts", spec: command_runner },
  { path: "src/usage/commands/served.ts", spec: command_served },
  { path: "src/usage/commands/ship.ts", spec: command_ship },
  { path: "src/usage/commands/show.ts", spec: command_show },
  { path: "src/usage/commands/showcase.ts", spec: command_showcase },
  { path: "src/usage/commands/start.ts", spec: command_start },
  { path: "src/usage/commands/status.ts", spec: command_status },
  { path: "src/usage/commands/submit.ts", spec: command_submit },
  { path: "src/usage/commands/sync.ts", spec: command_sync },
  { path: "src/usage/commands/token.ts", spec: command_token },
  { path: "src/usage/commands/unblock.ts", spec: command_unblock },
  { path: "src/usage/commands/undispatch.ts", spec: command_undispatch },
  { path: "src/usage/commands/unwrap.ts", spec: command_unwrap },
  { path: "src/usage/commands/update.ts", spec: command_update },
  { path: "src/usage/commands/wrap.ts", spec: command_wrap },
];
